// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package db

import (
	"context"
)

const countDocChunks = `-- name: CountDocChunks :one
SELECT COUNT(*) FROM chunks
WHERE doc_id = ?
`

func (q *Queries) CountDocChunks(ctx context.Context, docID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocChunks, docID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChunk = `-- name: CreateChunk :one
INSERT INTO chunks (doc_id, chunk_index, content)
VALUES (?, ?, ?)
RETURNING id, doc_id, chunk_index, content
`

type CreateChunkParams struct {
	DocID      int64  `json:"doc_id"`
	ChunkIndex int64  `json:"chunk_index"`
	Content    string `json:"content"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, createChunk, arg.DocID, arg.ChunkIndex, arg.Content)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.ChunkIndex,
		&i.Content,
	)
	return i, err
}

const deleteChunksByDoc = `-- name: DeleteChunksByDoc :exec
DELETE FROM chunks
WHERE doc_id = ?
`

func (q *Queries) DeleteChunksByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByDoc, docID)
	return err
}

const getChunk = `-- name: GetChunk :one
SELECT id, doc_id, chunk_index, content FROM chunks
WHERE id = ?
`

func (q *Queries) GetChunk(ctx context.Context, id int64) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, getChunk, id)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.ChunkIndex,
		&i.Content,
	)
	return i, err
}

const getChunkCountsByRepo = `-- name: GetChunkCountsByRepo :many
SELECT d.id AS doc_id, COUNT(c.id) AS chunk_count
FROM documents d
LEFT JOIN chunks c ON c.doc_id = d.id
WHERE d.repo_id = ?
GROUP BY d.id
`

type GetChunkCountsByRepoRow struct {
	DocID      int64 `json:"doc_id"`
	ChunkCount int64 `json:"chunk_count"`
}

func (q *Queries) GetChunkCountsByRepo(ctx context.Context, repoID int64) ([]GetChunkCountsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, getChunkCountsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChunkCountsByRepoRow{}
	for rows.Next() {
		var i GetChunkCountsByRepoRow
		if err := rows.Scan(&i.DocID, &i.ChunkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunks = `-- name: ListChunks :many
SELECT id, doc_id, chunk_index, content FROM chunks
WHERE doc_id = ?
ORDER BY chunk_index
`

func (q *Queries) ListChunks(ctx context.Context, docID int64) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, listChunks, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.ChunkIndex,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
