// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countRepoDocuments = `-- name: CountRepoDocuments :one
SELECT COUNT(*) FROM documents
WHERE repo_id = ?
`

func (q *Queries) CountRepoDocuments(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepoDocuments, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (repo_id, path, size, hash, mod_time, mime_type, language)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, repo_id, path, size, hash, mod_time, mime_type, language, created_at, updated_at
`

type CreateDocumentParams struct {
	RepoID   int64          `json:"repo_id"`
	Path     string         `json:"path"`
	Size     int64          `json:"size"`
	Hash     string         `json:"hash"`
	ModTime  time.Time      `json:"mod_time"`
	MimeType sql.NullString `json:"mime_type"`
	Language sql.NullString `json:"language"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.RepoID,
		arg.Path,
		arg.Size,
		arg.Hash,
		arg.ModTime,
		arg.MimeType,
		arg.Language,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Size,
		&i.Hash,
		&i.ModTime,
		&i.MimeType,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const deleteDocumentsByRepo = `-- name: DeleteDocumentsByRepo :exec
DELETE FROM documents
WHERE repo_id = ?
`

func (q *Queries) DeleteDocumentsByRepo(ctx context.Context, repoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsByRepo, repoID)
	return err
}

const documentExists = `-- name: DocumentExists :one
SELECT COUNT(*) FROM documents
WHERE repo_id = ? AND path = ?
`

type DocumentExistsParams struct {
	RepoID int64  `json:"repo_id"`
	Path   string `json:"path"`
}

func (q *Queries) DocumentExists(ctx context.Context, arg DocumentExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, documentExists, arg.RepoID, arg.Path)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, repo_id, path, size, hash, mod_time, mime_type, language, created_at, updated_at FROM documents
WHERE id = ?
`

func (q *Queries) GetDocument(ctx context.Context, id int64) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Size,
		&i.Hash,
		&i.ModTime,
		&i.MimeType,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByPath = `-- name: GetDocumentByPath :one
SELECT id, repo_id, path, size, hash, mod_time, mime_type, language, created_at, updated_at FROM documents
WHERE repo_id = ? AND path = ?
`

type GetDocumentByPathParams struct {
	RepoID int64  `json:"repo_id"`
	Path   string `json:"path"`
}

func (q *Queries) GetDocumentByPath(ctx context.Context, arg GetDocumentByPathParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByPath, arg.RepoID, arg.Path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.Size,
		&i.Hash,
		&i.ModTime,
		&i.MimeType,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, repo_id, path, size, hash, mod_time, mime_type, language, created_at, updated_at FROM documents
WHERE repo_id = ?
ORDER BY path
`

func (q *Queries) ListDocuments(ctx context.Context, repoID int64) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Path,
			&i.Size,
			&i.Hash,
			&i.ModTime,
			&i.MimeType,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents
SET size = ?,
    hash = ?,
    mod_time = ?,
    mime_type = ?,
    language = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDocumentParams struct {
	Size     int64          `json:"size"`
	Hash     string         `json:"hash"`
	ModTime  time.Time      `json:"mod_time"`
	MimeType sql.NullString `json:"mime_type"`
	Language sql.NullString `json:"language"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocument,
		arg.Size,
		arg.Hash,
		arg.ModTime,
		arg.MimeType,
		arg.Language,
		arg.ID,
	)
	return err
}
