// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Chunk struct {
	ID         int64  `json:"id"`
	DocID      int64  `json:"doc_id"`
	ChunkIndex int64  `json:"chunk_index"`
	Content    string `json:"content"`
}

type ChunksFt struct {
	Content string `json:"content"`
	DocID   string `json:"doc_id"`
}

type Document struct {
	ID        int64          `json:"id"`
	RepoID    int64          `json:"repo_id"`
	Path      string         `json:"path"`
	Size      int64          `json:"size"`
	Hash      string         `json:"hash"`
	ModTime   time.Time      `json:"mod_time"`
	MimeType  sql.NullString `json:"mime_type"`
	Language  sql.NullString `json:"language"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Metadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Repository struct {
	ID            int64          `json:"id"`
	Path          string         `json:"path"`
	Name          string         `json:"name"`
	RemoteUrl     sql.NullString `json:"remote_url"`
	Status        string         `json:"status"`
	LastIndexedAt sql.NullTime   `json:"last_indexed_at"`
	FileCount     int64          `json:"file_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
