// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountDocChunks(ctx context.Context, docID int64) (int64, error)
	CountRepoDocuments(ctx context.Context, repoID int64) (int64, error)
	CreateChunk(ctx context.Context, arg CreateChunkParams) (Chunk, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateRepo(ctx context.Context, arg CreateRepoParams) (Repository, error)
	DeleteChunksByDoc(ctx context.Context, docID int64) error
	DeleteDocument(ctx context.Context, id int64) error
	DeleteDocumentsByRepo(ctx context.Context, repoID int64) error
	DeleteRepo(ctx context.Context, id int64) error
	DocumentExists(ctx context.Context, arg DocumentExistsParams) (int64, error)
	GetChunk(ctx context.Context, id int64) (Chunk, error)
	GetChunkCountsByRepo(ctx context.Context, repoID int64) ([]GetChunkCountsByRepoRow, error)
	GetDocument(ctx context.Context, id int64) (Document, error)
	GetDocumentByPath(ctx context.Context, arg GetDocumentByPathParams) (Document, error)
	GetRepo(ctx context.Context, id int64) (Repository, error)
	GetRepoByPath(ctx context.Context, path string) (Repository, error)
	ListChunks(ctx context.Context, docID int64) ([]Chunk, error)
	ListDocuments(ctx context.Context, repoID int64) ([]Document, error)
	ListRepos(ctx context.Context) ([]Repository, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error
	UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) error
}

var _ Querier = (*Queries)(nil)
