// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refs.sql

package db

import (
	"context"
	"database/sql"
)

const createRef = `-- name: CreateRef :one
INSERT INTO refs (doc_id, name, line, col, context)
VALUES (?, ?, ?, ?, ?)
RETURNING id, doc_id, name, line, col, context
`

type CreateRefParams struct {
	DocID   int64  `json:"doc_id"`
	Name    string `json:"name"`
	Line    int64  `json:"line"`
	Col     int64  `json:"col"`
	Context string `json:"context"`
}

func (q *Queries) CreateRef(ctx context.Context, arg CreateRefParams) (Ref, error) {
	row := q.db.QueryRowContext(ctx, createRef,
		arg.DocID,
		arg.Name,
		arg.Line,
		arg.Col,
		arg.Context,
	)
	var i Ref
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.Name,
		&i.Line,
		&i.Col,
		&i.Context,
	)
	return i, err
}

const deleteRefsByDoc = `-- name: DeleteRefsByDoc :exec
DELETE FROM refs
WHERE doc_id = ?
`

func (q *Queries) DeleteRefsByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRefsByDoc, docID)
	return err
}

const findRefsByName = `-- name: FindRefsByName :many
SELECT r.id, r.doc_id, r.name, r.line, r.col, r.context, d.path, d.repo_id, r2.name AS repo_name
FROM refs r
JOIN documents d ON d.id = r.doc_id
JOIN repositories r2 ON r2.id = d.repo_id
WHERE r.name LIKE ? || '%'
ORDER BY r2.name, d.path, r.line
`

type FindRefsByNameRow struct {
	ID       int64  `json:"id"`
	DocID    int64  `json:"doc_id"`
	Name     string `json:"name"`
	Line     int64  `json:"line"`
	Col      int64  `json:"col"`
	Context  string `json:"context"`
	Path     string `json:"path"`
	RepoID   int64  `json:"repo_id"`
	RepoName string `json:"repo_name"`
}

func (q *Queries) FindRefsByName(ctx context.Context, dollar_1 sql.NullString) ([]FindRefsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, findRefsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRefsByNameRow{}
	for rows.Next() {
		var i FindRefsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Name,
			&i.Line,
			&i.Col,
			&i.Context,
			&i.Path,
			&i.RepoID,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRefsByNameAndRepo = `-- name: FindRefsByNameAndRepo :many
SELECT r.id, r.doc_id, r.name, r.line, r.col, r.context, d.path, d.repo_id, r2.name AS repo_name
FROM refs r
JOIN documents d ON d.id = r.doc_id
JOIN repositories r2 ON r2.id = d.repo_id
WHERE r2.name = ? AND r.name LIKE ? || '%'
ORDER BY d.path, r.line
`

type FindRefsByNameAndRepoParams struct {
	Name    string         `json:"name"`
	Column2 sql.NullString `json:"column_2"`
}

type FindRefsByNameAndRepoRow struct {
	ID       int64  `json:"id"`
	DocID    int64  `json:"doc_id"`
	Name     string `json:"name"`
	Line     int64  `json:"line"`
	Col      int64  `json:"col"`
	Context  string `json:"context"`
	Path     string `json:"path"`
	RepoID   int64  `json:"repo_id"`
	RepoName string `json:"repo_name"`
}

func (q *Queries) FindRefsByNameAndRepo(ctx context.Context, arg FindRefsByNameAndRepoParams) ([]FindRefsByNameAndRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, findRefsByNameAndRepo, arg.Name, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRefsByNameAndRepoRow{}
	for rows.Next() {
		var i FindRefsByNameAndRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Name,
			&i.Line,
			&i.Col,
			&i.Context,
			&i.Path,
			&i.RepoID,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
