// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package db

import (
	"context"
	"database/sql"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repositories (path, name, remote_url)
VALUES (?, ?, ?)
RETURNING id, path, name, remote_url, status, last_indexed_at, file_count, created_at, updated_at
`

type CreateRepoParams struct {
	Path      string         `json:"path"`
	Name      string         `json:"name"`
	RemoteUrl sql.NullString `json:"remote_url"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepo, arg.Path, arg.Name, arg.RemoteUrl)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.RemoteUrl,
		&i.Status,
		&i.LastIndexedAt,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repositories
WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const getRepo = `-- name: GetRepo :one
SELECT id, path, name, remote_url, status, last_indexed_at, file_count, created_at, updated_at FROM repositories
WHERE id = ?
`

func (q *Queries) GetRepo(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.RemoteUrl,
		&i.Status,
		&i.LastIndexedAt,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByPath = `-- name: GetRepoByPath :one
SELECT id, path, name, remote_url, status, last_indexed_at, file_count, created_at, updated_at FROM repositories
WHERE path = ?
`

func (q *Queries) GetRepoByPath(ctx context.Context, path string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepoByPath, path)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.RemoteUrl,
		&i.Status,
		&i.LastIndexedAt,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, path, name, remote_url, status, last_indexed_at, file_count, created_at, updated_at FROM repositories
WHERE name = ?
`

func (q *Queries) GetRepoByName(ctx context.Context, name string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepoByName, name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Name,
		&i.RemoteUrl,
		&i.Status,
		&i.LastIndexedAt,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT
  (SELECT COUNT(*) FROM repositories) AS repo_count,
  (SELECT COUNT(*) FROM documents) AS doc_count,
  (SELECT COUNT(*) FROM chunks) AS chunk_count,
  (SELECT COALESCE(SUM(size), 0) FROM documents) AS total_raw_bytes,
  (SELECT COALESCE(SUM(LENGTH(content)), 0) FROM chunks) AS total_chunk_bytes,
  (SELECT COUNT(*) FROM symbols) AS symbol_count,
  (SELECT COUNT(*) FROM refs) AS ref_count
`

type GetStatsRow struct {
	RepoCount       int64       `json:"repo_count"`
	DocCount        int64       `json:"doc_count"`
	ChunkCount      int64       `json:"chunk_count"`
	TotalRawBytes   interface{} `json:"total_raw_bytes"`
	TotalChunkBytes interface{} `json:"total_chunk_bytes"`
	SymbolCount     int64       `json:"symbol_count"`
	RefCount        int64       `json:"ref_count"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.RepoCount,
		&i.DocCount,
		&i.ChunkCount,
		&i.TotalRawBytes,
		&i.TotalChunkBytes,
		&i.SymbolCount,
		&i.RefCount,
	)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, path, name, remote_url, status, last_indexed_at, file_count, created_at, updated_at FROM repositories
ORDER BY name
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Name,
			&i.RemoteUrl,
			&i.Status,
			&i.LastIndexedAt,
			&i.FileCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoStatus = `-- name: UpdateRepoStatus :exec
UPDATE repositories
SET status = ?,
    last_indexed_at = ?,
    file_count = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRepoStatusParams struct {
	Status        string       `json:"status"`
	LastIndexedAt sql.NullTime `json:"last_indexed_at"`
	FileCount     int64        `json:"file_count"`
	ID            int64        `json:"id"`
}

func (q *Queries) UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoStatus,
		arg.Status,
		arg.LastIndexedAt,
		arg.FileCount,
		arg.ID,
	)
	return err
}
